### generated by argx/utils::convert-alias-file

# export alias sl = scratch-list #[entry]
export def --env sl [...xtags: string, --search(-s): string, --trash(-T), --hidden(-H), --important(-i): int, --urgent(-u): int, --challenge(-c): int, --updated: duration, --created: duration, --deadline: duration, --relevant(-r): int, --sort: list<string>, --done(-x): int, --raw, --md(-m), --md-list(-l), --scratch-tree, --debug, --accumulator(-a): any] {
    $env.config.hooks.pre_execution ++= [ { self-destruct: scratch code: 'print $"(ansi grey)load (ansi xterm_grey58)scratch(ansi grey)...(ansi reset)";use scratch *; $env.config.hooks.pre_execution = $env.config.hooks.pre_execution | where {|x| ($x | describe -d).type != record or $x.self-destruct? != scratch }' } ]; print $'(ansi grey)the next command will load the `(ansi xterm_grey58)scratch(ansi grey)` module.(ansi grey)'
}