export use systemctl.nu *
export use power.nu *
export use disk.nu *
export use archlinux.nu *
export use process.nu *
export use kill.nu *
export use clip.nu *
export use network.nu *
export use proxy.nu *
export use sh.nu *
export use web.nu *
export use qutebrowser.nu *
export use hyprland.nu *
export use zellij.nu *
export use asciinema.nu *
export use rbw.nu *
