### generated by argx/utils::convert-alias-file

# export alias mls = mc-ls #[entry]
export def --env mls [src: string] {
    $env.config.hooks.pre_execution ++= [ { self-destruct: minio code: 'print $"(ansi grey)load (ansi xterm_grey58)minio(ansi grey)...(ansi reset)";use minio *; $env.config.hooks.pre_execution = $env.config.hooks.pre_execution | where {|x| ($x | describe -d).type != record or $x.self-destruct? != minio }' } ]; print $'(ansi grey)the next command will load the `(ansi xterm_grey58)minio(ansi grey)` module.(ansi grey)'
}