### generated by argx/utils::convert-alias-file

# export alias mls = mc-ls #[entry]
export def --env mls [src: string] {
    $env.config.hooks.pre_execution = [ { code: 'print $"(ansi grey)load minio...(ansi reset)";use minio *; $env.config.hooks.pre_execution = ($env.config.hooks.pre_execution | slice ..-2)' } ]
    print $'(ansi grey)re-execute to load...(ansi grey)'
}